"""Rules shared across supported Warhammer 40,000 editions."""

D6_SIDES = 6
LOWEST_NATURAL_ROLL = 1
HIGHEST_NATURAL_ROLL = D6_SIDES
BEST_D6_TARGET = 2
IMPOSSIBLE_D6_TARGET = D6_SIDES + 1

MINIMUM_NAME_LENGTH = 1
MAXIMUM_NAME_LENGTH = 100
