"""Warhammer 40,000 11th-edition constraints used by the application."""

EDITION = 11

MINIMUM_UNIT_SIZE = 1
MAXIMUM_UNIT_SIZE = 20

MINIMUM_MOVEMENT = 0
MAXIMUM_MOVEMENT = 100

BEST_HIT_ROLL = 2
WORST_HIT_ROLL = 6

BEST_ARMOUR_SAVE = 2
NO_ARMOUR_SAVE = 7

BEST_INVULNERABLE_SAVE = 2
WORST_INVULNERABLE_SAVE = 6

MINIMUM_LEADERSHIP = 2
MAXIMUM_LEADERSHIP = 12

MINIMUM_OBJECTIVE_CONTROL = 0
MAXIMUM_OBJECTIVE_CONTROL = 100

MINIMUM_POINTS = 0

MINIMUM_ATTACKS = 1
MAXIMUM_ATTACKS = 1000

MINIMUM_WEAPON_RANGE = 1
MAXIMUM_WEAPON_RANGE = 1000

MINIMUM_STRENGTH = 1
MAXIMUM_STRENGTH = 100

MINIMUM_TOUGHNESS = 1
MAXIMUM_TOUGHNESS = 100

MINIMUM_DAMAGE = 1
MAXIMUM_DAMAGE = 100

MINIMUM_WOUNDS = 1
MAXIMUM_WOUNDS = 100

MINIMUM_ARMOUR_PENETRATION = -10
MAXIMUM_ARMOUR_PENETRATION = 0
